[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x"
#runner = "elf2uf2-rs -d"
#runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
# The cyw43 crate is quite chatty on debug, logging all HCI traffic.
DEFMT_LOG = "debug,cyw43=info"
PROBE_RS_CHIP = "rp235x"
